# Interactive notebook used to prepare code parts for Azure ML

### Load data

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load raw data
df = pd.read_csv("../data/lending_club.csv")

df.head()

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
0,10000.0,36 months,11.44,329.48,B,B4,Marketing,10+ years,RENT,117000.0,...,16.0,0.0,36369.0,41.8,25.0,w,INDIVIDUAL,0.0,0.0,"0174 Michelle Gateway\r\nMendozaberg, OK 22690"
1,8000.0,36 months,11.99,265.68,B,B5,Credit analyst,4 years,MORTGAGE,65000.0,...,17.0,0.0,20131.0,53.3,27.0,f,INDIVIDUAL,3.0,0.0,"1076 Carney Fort Apt. 347\r\nLoganmouth, SD 05113"
2,15600.0,36 months,10.49,506.97,B,B3,Statistician,< 1 year,RENT,43057.0,...,13.0,0.0,11987.0,92.2,26.0,f,INDIVIDUAL,0.0,0.0,"87025 Mark Dale Apt. 269\r\nNew Sabrina, WV 05113"
3,7200.0,36 months,6.49,220.65,A,A2,Client Advocate,6 years,RENT,54000.0,...,6.0,0.0,5472.0,21.5,13.0,f,INDIVIDUAL,0.0,0.0,"823 Reid Ford\r\nDelacruzside, MA 00813"
4,24375.0,60 months,17.27,609.33,C,C5,Destiny Management Inc.,9 years,MORTGAGE,55000.0,...,13.0,0.0,24584.0,69.8,43.0,f,INDIVIDUAL,1.0,0.0,"679 Luna Roads\r\nGreggshire, VA 11650"

### Prepare data

In [5]:
# Get random 10 rows
df = df.sample(10)
df

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
6578,20000.0,60 months,16.55,492.23,D,D2,letter carrier,10+ years,RENT,59000.0,...,14.0,0.0,34693.0,94.3,24.0,w,INDIVIDUAL,2.0,0.0,"2643 Irwin Gateway\r\nWellsfurt, VA 30723"
159904,35000.0,36 months,14.47,1204.23,C,C2,NaN,9 years,MORTGAGE,123000.0,...,33.0,0.0,37226.0,56.7,55.0,w,INDIVIDUAL,3.0,0.0,"1921 Todd Views\r\nDaisyton, AR 22690"
165022,33025.0,36 months,18.25,1198.08,E,E1,pharmacist,10+ years,MORTGAGE,167000.0,...,12.0,0.0,51287.0,61.9,58.0,w,INDIVIDUAL,4.0,0.0,"PSC 5738, Box 2197\r\nAPO AE 48052"
36585,28000.0,36 months,18.49,1019.17,D,D2,Sears Holdings,2 years,RENT,70000.0,...,15.0,0.0,26408.0,66.2,26.0,f,INDIVIDUAL,0.0,0.0,"95675 Harvey Union\r\nNicholasfort, NM 86630"
279894,1800.0,36 months,10.49,58.50,B,B3,driver,10+ years,RENT,35000.0,...,6.0,1.0,2545.0,44.6,58.0,w,INDIVIDUAL,0.0,1.0,"434 Johnson Mill Apt. 052\r\nNorth Ryan, WV 48052"
388719,13000.0,36 months,14.99,450.59,C,C5,Registered Nurse,10+ years,OWN,96000.0,...,7.0,0.0,7324.0,49.8,20.0,f,INDIVIDUAL,6.0,0.0,Unit 2638 Box 5192\r\nDPO AA 29597
296240,5000.0,36 months,7.89,156.43,A,A5,Concierge,10+ years,RENT,50000.0,...,13.0,0.0,6653.0,29.4,21.0,w,INDIVIDUAL,0.0,0.0,2518 Sean Highway Suite 788\r\nLake Danielport...
100914,17325.0,36 months,12.49,579.51,B,B5,NaN,NaN,MORTGAGE,39250.0,...,16.0,1.0,17756.0,57.3,46.0,f,INDIVIDUAL,5.0,1.0,"9933 Mejia Branch\r\nLake Anthony, DC 30723"
3502,4000.0,36 months,12.74,134.28,C,C1,general service tech,< 1 year,MORTGAGE,45000.0,...,12.0,1.0,12158.0,35.7,21.0,f,INDIVIDUAL,3.0,1.0,"231 Bell Via\r\nEast Kevinmouth, KY 05113"
66205,12225.0,60 months,20.99,330.66,E,E5,NaN,NaN,RENT,36000.0,...,9.0,1.0,5963.0,66.3,13.0,w,INDIVIDUAL,0.0,0.0,265 Gonzalez Pine Suite 052\r\nLake Michaelfur...

In [17]:
# Generate some changes to simulate new data
df['loan_amnt'].iloc[0] = 25000
df['loan_amnt'].iloc[3] = 35000
df['int_rate'].iloc[1] = 16.11
df['int_rate'].iloc[2] = 16.11
df['home_ownership'].iloc[4] = "RENT"
df['home_ownership'].iloc[5] = "RENT"
df['home_ownership'].iloc[6] = "RENT"
df['emp_length'].iloc[7] = "9 years"
df['emp_length'].iloc[8] = "9 years"
df['emp_length'].iloc[9] = "9 years"
df = df.drop('loan_status', axis=1)
df

C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['loan_amnt'].iloc[0] = 25000
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['loan_amnt'].iloc[3] = 35000
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['int_rate'].iloc[1] = 16.11
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['int_rate'].iloc[2] = 16.11
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['home_ownership'].iloc[4] = "RENT"
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['home_ownership'].iloc[5] = "RENT"
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['home_ownership'].iloc[6] = "RENT"
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emp_length'].iloc[7] = "9 years"
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emp_length'].iloc[8] = "9 years"
C:\Users\tokubica\AppData\Local\Temp\ipykernel_13764\4262237648.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['emp_length'].iloc[9] = "9 years"

,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,...,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,application_type,mort_acc,pub_rec_bankruptcies,address
6578,25000.0,60 months,16.55,492.23,D,D2,letter carrier,10+ years,RENT,59000.0,...,14.0,0.0,34693.0,94.3,24.0,w,INDIVIDUAL,2.0,0.0,"2643 Irwin Gateway\r\nWellsfurt, VA 30723"
159904,35000.0,36 months,16.11,1204.23,C,C2,NaN,9 years,MORTGAGE,123000.0,...,33.0,0.0,37226.0,56.7,55.0,w,INDIVIDUAL,3.0,0.0,"1921 Todd Views\r\nDaisyton, AR 22690"
165022,33025.0,36 months,16.11,1198.08,E,E1,pharmacist,10+ years,MORTGAGE,167000.0,...,12.0,0.0,51287.0,61.9,58.0,w,INDIVIDUAL,4.0,0.0,"PSC 5738, Box 2197\r\nAPO AE 48052"
36585,35000.0,36 months,18.49,1019.17,D,D2,Sears Holdings,2 years,RENT,70000.0,...,15.0,0.0,26408.0,66.2,26.0,f,INDIVIDUAL,0.0,0.0,"95675 Harvey Union\r\nNicholasfort, NM 86630"
279894,1800.0,36 months,10.49,58.50,B,B3,driver,10+ years,RENT,35000.0,...,6.0,1.0,2545.0,44.6,58.0,w,INDIVIDUAL,0.0,1.0,"434 Johnson Mill Apt. 052\r\nNorth Ryan, WV 48052"
388719,13000.0,36 months,14.99,450.59,C,C5,Registered Nurse,10+ years,RENT,96000.0,...,7.0,0.0,7324.0,49.8,20.0,f,INDIVIDUAL,6.0,0.0,Unit 2638 Box 5192\r\nDPO AA 29597
296240,5000.0,36 months,7.89,156.43,A,A5,Concierge,10+ years,RENT,50000.0,...,13.0,0.0,6653.0,29.4,21.0,w,INDIVIDUAL,0.0,0.0,2518 Sean Highway Suite 788\r\nLake Danielport...
100914,17325.0,36 months,12.49,579.51,B,B5,NaN,9 years,MORTGAGE,39250.0,...,16.0,1.0,17756.0,57.3,46.0,f,INDIVIDUAL,5.0,1.0,"9933 Mejia Branch\r\nLake Anthony, DC 30723"
3502,4000.0,36 months,12.74,134.28,C,C1,general service tech,9 years,MORTGAGE,45000.0,...,12.0,1.0,12158.0,35.7,21.0,f,INDIVIDUAL,3.0,1.0,"231 Bell Via\r\nEast Kevinmouth, KY 05113"
66205,12225.0,60 months,20.99,330.66,E,E5,NaN,9 years,RENT,36000.0,...,9.0,1.0,5963.0,66.3,13.0,w,INDIVIDUAL,0.0,0.0,265 Gonzalez Pine Suite 052\r\nLake Michaelfur...

In [14]:
# Save preprocessed data for use with AutoML before making OHE
df.to_csv("../data/lending_club_inferencing.csv", index=False)